using POC.Localization.Framework;
using System.ComponentModel;
using System.Globalization;
using System.Windows.Input;
using System.Windows.Markup;

namespace POC.Localization.WPF.Framework;
public class CLocaliseExtension : MarkupExtension, INotifyPropertyChanged
{
    #region Constructor

    public CLocaliseExtension()
    {
        // singleton access not optimal here, see if DI is possible in a markup extension
        CStringLocalizerService.Instance.CultureChanged += (sender, e) => OnPropertyChanged(nameof(Value));
    } 

    #endregion

    #region MarkupExtension Members

    /// <summary>
    /// Instead of providing the value directly here, we use an intermediate property Value to allow for data binding, which in turn allows notifying property changed.
    /// </summary>
    public override object ProvideValue(IServiceProvider serviceProvider)
    {
        return this;
    }

    #endregion

    #region Description

    /// <summary>
    /// Since we cannot perform a <code>nameof()</code> in a markup extension, we use an autogenerated resource class to get the key from the property name.
    /// </summary>
    public IResourceProvider ResourceProvider { get; set; } = null!;

    /// <summary>
    /// For displaying purpose only, allows notifying property changed on the markup extension
    /// </summary>
    public string Value
    {
        get
        {
            string correspondingKey = CResourceHelper.GetResourceKeyFromPropertyName(ResourceProvider.ResourcePropertyName);
            return CStringLocalizerService.Instance.Translate(CStringLocalizerService.Instance.SelectedCulture, correspondingKey);
        }
    }


    #endregion
    #region INotifyPropertyChanged

    public event PropertyChangedEventHandler? PropertyChanged;
    protected void OnPropertyChanged(string name) => PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(name)); 

    #endregion
}