namespace POC.Localization.WPF.Framework;
/// <summary>
/// This is an intermediate interface to allow for a simple way to get the property name of a static Resource class, which itself is autogenerated from a resx file. It allows to bypass the impossibility of using nameof() in a markup extension.
/// </summary>
public interface IResourceProvider
{
    public string ResourcePropertyName { get; }
}
