namespace POC.Localization.Framework;
using System.Globalization;
using System.Reflection;
using System;
using System.IO;
using System.Reflection.Metadata;
using System.Reflection.PortableExecutable;
using System.Reflection.Metadata.Ecma335;

public static class CResourceHelper
{
    /// <summary>
    /// This is a simple version where resx autogenerated properties are converted to their equivalent key. This assumes that by convention no underscore or hyphen can be used in the key.
    /// </summary>
    public static string GetResourceKeyFromPropertyName(string _strResourcePropertyName)
    {
        return _strResourcePropertyName.Replace("_", ".");
    }

    /// <summary>
    /// This is a complexe version where the key is extracted from the getter method of a property in a resource class. This is used to get the key from the autogenerated resource class. Using this allows to have no restriction on the key name, at the cost of performance when retrieving the key.
    /// </summary>
    public static string? GetResourceKeyFromGetter(
        string assemblyPath,
        string resourceTypeName,
        string getterMethodName)
    {
        using var stream = File.OpenRead(assemblyPath);
        using var peReader = new PEReader(stream);

        if (!peReader.HasMetadata)
            throw new InvalidOperationException("Not a valid .NET assembly.");

        var metadataReader = peReader.GetMetadataReader();

        foreach (var typeHandle in metadataReader.TypeDefinitions)
        {
            var typeDef = metadataReader.GetTypeDefinition(typeHandle);
            var typeName = metadataReader.GetString(typeDef.Name);
            var typeNamespace = metadataReader.GetString(typeDef.Namespace);
            var fullTypeName = string.IsNullOrEmpty(typeNamespace)
                ? typeName
                : $"{typeNamespace}.{typeName}";

            if (fullTypeName != resourceTypeName)
                continue;

            foreach (var methodHandle in typeDef.GetMethods())
            {
                var methodDef = metadataReader.GetMethodDefinition(methodHandle);
                var methodName = metadataReader.GetString(methodDef.Name);

                if (methodName != getterMethodName)
                    continue;

                // Get method body and IL reader
                var body = peReader.GetMethodBody(methodDef.RelativeVirtualAddress);
                var ilReader = body.GetILReader();

                while (ilReader.RemainingBytes > 0)
                {
                    var code = ilReader.ReadByte();

                    if (code == 0xFE)
                    {
                        code = ilReader.ReadByte(); // Skip two-byte opcodes
                        continue;
                    }

                    if (code == 0x72) // ldstr
                    {
                        int token = ilReader.ReadInt32();
                        var handle = MetadataTokens.UserStringHandle(token);
                        if (handle.IsNil)
                            return null;

                        return metadataReader.GetUserString(handle);
                    }

                    // For a robust parser, you'd want to skip over operand data here
                }
            }

            break; // Only process the matched type
        }

        return null;
    }
}