<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\POC.Localization.Framework\POC.Localization.Framework.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resource\POC_Localization_Plugin1.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>POC_Localization_Plugin1.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resource\POC_Localization_Plugin1.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>POC_Localization_Plugin1.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
