using POC.Localization.Framework;
using POC.Localization.WPF.Framework;
using System.Globalization;
using System.Text.RegularExpressions;
using System.Transactions;
using System.Windows;
using static System.Net.Mime.MediaTypeNames;
using System.Windows.Media.Effects;
using POC.Localization.Plugin1.Resource;
using System.Collections.ObjectModel;

namespace POC.Localization.WPF.App;
/// <summary>
/// Interaction logic for MainWindow.xaml
/// </summary>
public partial class MainWindow : Window
{
    public static string TestCulture1 = CultureInfo.CurrentCulture.Name;
    public static string TestCulture2 = "en-US";

    public MainWindow()
    {
        LoadTranslations(); // this should be done elswehere, e.g. in a bootstrapper
        LoadChatMessages();
        InitializeComponent();
    }

    public ObservableCollection<ChatMessageViewModel> ChatMessageViewModels { get; } = new();

    private void LoadTranslations()
    {
        // real context: get translation keys and texts from online database
        // poc context: use the resx resource autogenerated from file
        AddTranslationMock(TestCulture1);
        AddTranslationMock(TestCulture2);

    }
    private void AddTranslationMock(string _strCulture)
    {
        // for the sake of demonstration, append culture to text to visualize effect on translation

        // UI
        CStringLocalizerService.Instance.AddTranslation(
        TestCulture2,
            CResourceHelper.GetResourceKeyFromPropertyName(nameof(POC_Localization_WPF_App.UI_Text)),
            POC_Localization_WPF_App.UI_Text + " " + _strCulture);

        CStringLocalizerService.Instance.AddTranslation(
            TestCulture2,
            CResourceHelper.GetResourceKeyFromPropertyName(nameof(POC_Localization_WPF_App.UI_Text2)),
            POC_Localization_WPF_App.UI_Text2 + " " + _strCulture);

        CStringLocalizerService.Instance.AddTranslation(
            TestCulture2,
            CResourceHelper.GetResourceKeyFromPropertyName(nameof(POC_Localization_WPF_App.UI_Text3)),
            POC_Localization_WPF_App.UI_Text3 + " " + _strCulture);

        // PLUGIN
        // in real context, we do not have direct access to plugin, this is simplified in the poc
        CStringLocalizerService.Instance.AddTranslation(
            TestCulture2,
            CResourceHelper.GetResourceKeyFromPropertyName(nameof(POC_Localization_Plugin1.POC_Localization_Plugin1_Parameter1_AAAA)),
            POC_Localization_Plugin1.POC_Localization_Plugin1_Parameter1_AAAA + " " + _strCulture);

        CStringLocalizerService.Instance.AddTranslation(
            TestCulture2,
            CResourceHelper.GetResourceKeyFromPropertyName(nameof(POC_Localization_Plugin1.POC_Localization_Plugin1_SecondParameter)),
            POC_Localization_Plugin1.POC_Localization_Plugin1_SecondParameter + " " + _strCulture);
    }

    private void LoadChatMessages()
    {
        // this is a poc simulation to load chat message keys from the plugin, real context scenario involves online reception of the key
        ChatMessageViewModels.Add(new ChatMessageViewModel(CResourceHelper.GetResourceKeyFromPropertyName(nameof(POC_Localization_Plugin1.POC_Localization_Plugin1_Parameter1_AAAA))));
        ChatMessageViewModels.Add(new ChatMessageViewModel(CResourceHelper.GetResourceKeyFromPropertyName(nameof(POC_Localization_Plugin1.POC_Localization_Plugin1_SecondParameter))));
    }

    private void TranslateToCulture1(object sender, RoutedEventArgs e)
    {
        CStringLocalizerService.Instance.UpdateCulture(TestCulture1);
    }

    private void TranslateToCulture2(object sender, RoutedEventArgs e)
    {
        CStringLocalizerService.Instance.UpdateCulture(TestCulture2);
    }
}