<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\POC.Localization.Plugin1\POC.Localization.Plugin1.csproj" />
    <ProjectReference Include="..\POC.Localization.WPF.Framework\POC.Localization.WPF.Framework.csproj" />
    <ProjectReference Include="..\ResxKeyWrapperGen\ResxKeyWrapperGen.csproj" OutputItemType="Analyzer" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="POC_Localization_WPF_App.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>POC_Localization_WPF_App.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="POC_Localization_WPF_App.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>POC_Localization_WPF_App.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
